import React from 'react';
import Credential from '../components/Credential';
import Navbar from '../components/Navbar';
import { useAuth } from '../context/AuthContext';
import Login from '../components/Login';
import Head from 'next/head';
import Form from '../components/Form';
import Validator from '../components/Validator';

export default function Home() {
	const { currentUser } = useAuth();
	return (
		<div>
			<Head>
				<title>Bienvenido!</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="https://www.cervezasalta.com.ar/img/logo-salta.png" />
			</Head>
			<div>
				<Validator />
				<Navbar />
				{/* if(currentUser.email === User.email) */}
				<Credential />
				{/* else {
					
				} */}
				<Form />
				{!currentUser && <Login />}
			</div>
		</div>
	);
}
