import React from 'react';
import Credential from '../components/Credential';
import Navbar from '../components/Navbar';
import { useAuth } from '../context/AuthContext';
import Login from '../components/Login';
import Head from 'next/head';
import Form from '../components/Form';

import app from '../firebase';
import { getFirestore, collection, addDoc, getDocs, doc, deleteDoc, getDoc, setDoc } from 'firebase/firestore';

const db = getFirestore(app);

export default function Home({ users }) {
	const { currentUser } = useAuth();
	if (currentUser) {
		const userLoged = users?.find(user => user.email === currentUser.email);
		return (
			<div>
				<Head>
					<title>Bienvenido!</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="https://www.cervezasalta.com.ar/img/logo-salta.png" />
				</Head>
				<div>
					<Navbar />
					{userLoged && <Credential props={userLoged} />}
					{!userLoged && <Form />}
				</div>
			</div>
		);
	} else {
		return <Login />;
	}
}

export const getServerSideProps = async context => {
	const querySnapshot = await getDocs(collection(db, 'users'));
	const docs = [];
	querySnapshot.forEach(doc => {
		docs.push({ ...doc.data(), id: doc.id });
	});

	return {
		props: {
			users: docs,
		},
	};
};
